#!/bin/bash

# Install jq if not installed
if ! command -v jq &> /dev/null; then
    echo "Installing jq..."
    sudo apt-get update
    sudo apt-get install -y jq
fi

# Install wslvar if not installed
if ! command -v wslvar &> /dev/null; then
    echo "Installing wslvar..."
    sudo apt-get install -y wslu
fi

load_gnome_profile=false
load_wsl_profile=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --gnome) load_gnome_profile=true ;;
    --wsl) load_wsl_profile=true ;;
    *) echo "Invalid option: $1"
       exit 1 ;;
  esac
  shift
done

# Check if either GNOME or WSL profile should be loaded
if $load_gnome_profile; then
  # Load the GNOME profile
  dconf load /org/gnome/terminal/legacy/profiles:/ < configs/gnome-profile.dconf
elif $load_wsl_profile; then
  # Load the WSL profile
  windows_username=$(wslvar -s USERNAME)

  # Define the path to the Windows Terminal settings.json file
  SETTINGS_FILE="/mnt/c/Users/$windows_username/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"

  # Define the new color scheme
  NEW_SCHEME='
  {
      "background": "#383838",
      "black": "#101116",
      "blue": "#3E87FA",
      "brightBlack": "#686868",
      "brightBlue": "#6871FF",
      "brightCyan": "#60FDFF",
      "brightGreen": "#5FFA68",
      "brightPurple": "#D682EC",
      "brightRed": "#FF6E67",
      "brightWhite": "#FFFFFF",
      "brightYellow": "#FFFC67",
      "cursorColor": "#FFFFFF",
      "cyan": "#00F7FF",
      "foreground": "#B8FFE1",
      "green": "#00FF9C",
      "name": "Blue Matrix",
      "purple": "#D57BFF",
      "red": "#FF0000",
      "selectionBackground": "#FFFFFF",
      "white": "#C7C7C7",
      "yellow": "#FFE400"
  }
  '

  # Read the existing settings.json file
  CONFIG_JSON=$(<"$SETTINGS_FILE")

  # Add the new color scheme to the "schemes" section
  CONFIG_JSON=$(echo "$CONFIG_JSON" | jq ".schemes += [$NEW_SCHEME]")

  # Set the new color scheme as the default
  CONFIG_JSON=$(echo "$CONFIG_JSON" | jq '.defaults.colorScheme = "Blue Matrix"')

 # Write the updated JSON back to the settings file
  echo "$CONFIG_JSON" > "$SETTINGS_FILE"

  echo "New color scheme 'Blue Matrix' added to $SETTINGS_FILE and set as default for user $windows_username."

else
  echo "Please specify either --gnome or --wsl as an option."
  exit 1
fi


# Creating bashrc
cat configs/bashrc > ~/.bashrc
# Installing
sudo apt -y install tmux xclip fonts-powerline
# Creating tmux config
cat configs/tmuxconf > ~/.tmux.conf
# Instaling tpm for tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/scripts/install_plugins.sh
~/.tmux/plugins/tpm/scripts/source_plugins.sh

# Set the path to your TTF file
TTF_FILE="fonts/CaskaydiaCoveNerdFontMono-Regular.ttf"

# Check if the TTF file exists
if [ ! -f "$TTF_FILE" ]; then
    echo "Font file not found: $TTF_FILE"
    exit 1
fi

# Set the directory where system fonts are stored
FONT_DIR="/usr/share/fonts/"
# Copy the TTF file to the system fonts directory
sudo cp "$TTF_FILE" "$FONT_DIR"
# Update the font cache
sudo fc-cache -f

tmux source ~/.tmux.conf
source ~/.bashrc

